### ISSUE TITLE
option to enable/disable the plugin

### ISSUE THREAD

**Issue by flosch-hb** [MikeSouza/serverless-associate-waf#18]
Hello,

The plugin works nicely, thanks for the work :)

I have a project that is deployed in both AWS Global and AWS China.
That last one is a bit specific and WAF service is not available there.

I wonder if it would be possible to have a boolean flag that we could pass to the plugin config to enable/disable it for specific cases such as China?

```
custom:
  associateWaf:
    name: {some-WAF-name}
    enabled: ${self:custom.isRegionalWafEnabled}
```
