### ISSUE TITLE
Use existing WAF with plugin

### ISSUE THREAD

**Issue by iwt-kschoenrock** [MikeSouza/serverless-associate-waf#30]
Hello! I'm trying to use a WAF created with Terraform with the serverless-associate-waf plugin, but I get the following error when trying to deploy:

````
Error: The CloudFormation template is invalid: Unresolved resource dependencies [ApiGatewayRestApi] in the Outputs block of the template
````

The offending snippet seems to be this, at the end of `cloudformation-template-update-stack.json`:

````yaml
...
"ApiGatewayRestApiWaf": {
  "Description": "Rest API Id",
  "Value": {
    "Ref": "ApiGatewayRestApi"
  }
}
````

I've configured the plugin as follows (only the changes introduced):

`serverless.yaml`:
````yaml
custom:
  stages:
    stageName:
      waf_name: stageName-acl
  associateWaf:
    name: ${self:custom.stages.${self:provider.stage}.waf_name}
    version: Regional

plugins:
  - serverless-associate-waf

````

The WAF (classic) is named `stageName-acl`, as verified on the AWS Console, but I see no mention of it in the Cloudformation files. Am I doing something wrong?

Versions:

````
$ sls --version
Framework Core: 2.4.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
````

`serverless-associate-waf`: `1.2.1`
