### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by davidfarinha** [MikeSouza/serverless-associate-waf#6]
Hello,
I'm wondering what value exactly I need to provide as "myRegionalWaf".
For reference- I have the following configuration:
```yaml
custom:
  associateWaf:
    name: myRegionalWaf
resources:
  Resources:
    WebACL:
      Type: "AWS::WAF::WebACL"
      Properties:
        DefaultAction:
          Type: BLOCK
        MetricName: "TrustedIPs"
        Name: "WebACLTrustedIps"
        Rules:
          - Action:
              Type: ALLOW
            Priority: 1
            RuleId: {Ref: WAFRule}
    WAFRule:
      Type: "AWS::WAF::Rule"
      Properties:
        Name: "IPSetRuleWhitelistedIps"
        MetricName: "MyIPSetRule"
        Predicates:
          - DataId: {Ref: WAFIpSet}
            Negated: false
            Type: "IPMatch"
    WAFIpSet:
      Type: "AWS::WAF::IPSet"
      Properties:
        IPSetDescriptors:
          - Type: "IPV4"
            Value: "xxxxxxxx/32"
        Name: "IPSetWhitelistedIps"
```
@MikeSouza @vasudevan-palani
